module.exports = {
  plugins: [
    require("@trivago/prettier-plugin-sort-imports"),
    require("prettier-plugin-tailwindcss"),
  ],
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  quoteProps: "as-needed",
  jsxSingleQuote: false,
  trailingComma: "es5",
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  proseWrap: "preserve",
  htmlWhitespaceSensitivity: "css",
  endOfLine: "lf",
  embeddedLanguageFormatting: "auto",
  singleAttributePerLine: false,
  importOrder: [
    "^types.*",
    "^app.*",
    "^assets.*",
    "^components.*",
    "^constants.*",
    "^contexts.*",
    "^contracts.*",
    "^errors.*",
    "^helpers.*",
    "^pages.*",
    "^schemas.*",
    "^services.*",
    "^slices.*",
    "^store.*",
    "^[../]",
    "^[./]",
  ],
};
